import * as React from "react";
import AppBar from "@mui/material/AppBar";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
import IconButton from "@mui/material/IconButton";
import Typography from "@mui/material/Typography";
import Menu from "@mui/material/Menu";
import MenuIcon from "@mui/icons-material/Menu";
import Container from "@mui/material/Container";
import Avatar from "@mui/material/Avatar";
import Button from "@mui/material/Button";
import Tooltip from "@mui/material/Tooltip";
import MenuItem from "@mui/material/MenuItem";
import Head from "next/head";

const pages = ["Products", "Developers", "Pricing", "Company"];
const settings = ["Profile", "Account", "Dashboard", "Logout"];

export default function ButtonAppBar() {
  const [anchorElNav, setAnchorElNav] = React.useState<null | HTMLElement>(
    null
  );
  const [anchorElUser, setAnchorElUser] = React.useState<null | HTMLElement>(
    null
  );

  const handleOpenNavMenu = (event: React.MouseEvent<HTMLElement>) => {
    setAnchorElNav(event.currentTarget);
  };
  const handleOpenUserMenu = (event: React.MouseEvent<HTMLElement>) => {
    setAnchorElUser(event.currentTarget);
  };

  const handleCloseNavMenu = () => {
    setAnchorElNav(null);
  };

  const handleCloseUserMenu = () => {
    setAnchorElUser(null);
  };

  return (
    <Box sx={{ flexGrow: 1 }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/atelier-cave-dark.min.css"/>
      </Head>
      <AppBar sx={{ bgcolor: "#41AACB" }} position="static">
        <Container maxWidth="lg">
          <Toolbar>
            <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
              AirDady
            </Typography>
            <Box display="flex">
              <Box sx={{ flexGrow: 1, display: { xs: "none", md: "flex" } }}>
                {pages.map((page) => (
                  <Button
                    key={page}
                    sx={{
                      m: 2,
                      color: "white",
                      textTransform: "capitalize",
                      display: "block",
                      fontFamily: "poppins",
                      fontWeight: 300,
                    }}
                  >
                    {page}
                  </Button>
                ))}
              </Box>
              <Button
                sx={{
                    m: 2,
                    textTransform: "capitalize",
                    display: "block",
                    fontFamily: "poppins",
                    fontWeight: 400,
                    backgroundColor: 'white',
                    color:"black",
                    px:3
                  }}
              >
                Login
              </Button>
              <Button
                sx={{
                  m: 2,
                  ml:2,
                  textTransform: "capitalize",
                  display: "block",
                  fontFamily: "poppins",
                  fontWeight: 400,
                  backgroundColor: '#008BB7',
                  color:"white",
                  px:3,
                  py:1
                }}
                color="inherit"
                size="small"
              >
                Get Api Keys
              </Button>
            </Box>
          </Toolbar>
        </Container>
      </AppBar>
    </Box>
  );
}
