import Head from "next/head";
import Container from "@mui/material/Container";
import Box from "@mui/material/Box";
import AppBar from "@mui/material/AppBar";
import Typography from "@mui/material/Typography";
import { Button } from "antd";
import "antd/dist/antd.css";

import CheckCircleRoundedIcon from "@mui/icons-material/CheckCircleRounded";
import Toolbar from "@mui/material/Toolbar";

interface MsgProps {
  mainText?: string;
  subText?: string;
}

const Message = ({ mainText, subText }: MsgProps) => {
  const onFinish = (values: any) => {
    console.log("Received values of form: ", values);
  };

  return (
    <Box>
      <Head>
        <title>AirDady</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <AppBar
        style={{ background: "#ffffff" }}
        sx={{ boxShadow: 0, paddingLeft: 5, paddingTop: 3 }}
      >
        <Toolbar variant="dense">
          <Typography variant="h4" color="#008BB7" component="div">
            Airdady
          </Typography>
        </Toolbar>
      </AppBar>

      <Container fixed>
        <Box
          sx={{
            height: "70vh",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <Box sx={{ width: "100%" }}>
            <CheckCircleRoundedIcon
              sx={{
                fontSize: 100,
                color: "#139750",
              }}
            />
            <Box textAlign="center" mb={3}>
              <Typography variant="h6">{mainText}</Typography>
              <Typography variant="body2">{subText}</Typography>
            </Box>
            <Button type="primary" htmlType="submit">
              Send
            </Button>
          </Box>
        </Box>
      </Container>
    </Box>
  );
};

export default Message;
