import * as React from "react";
import AppBar from "@mui/material/AppBar";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";
import Container from "@mui/material/Container";
import Head from "next/head";
import Link from "next/link";

export default function PlainAppBar() {
  return (
    <Box sx={{ flexGrow: 1 }}>
      <Head>
        <title>AirDady</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Container maxWidth="lg">
        <AppBar
          style={{ background: "#ffffff" }}
          sx={{ boxShadow: 0, paddingLeft: 5, paddingTop: 3 }}
        >
          <Toolbar variant="dense">
            <Link href="/" passHref>
              <Typography variant="h4" color="#008BB7" component="div">
                Airdady
              </Typography>
            </Link>
          </Toolbar>
        </AppBar>
      </Container>
    </Box>
  );
}
